# Generated by Django 2.0.3 on 2018-05-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eth_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_name', models.CharField(max_length=30, verbose_name='own_name')),
                ('pic_hash', models.CharField(max_length=32, verbose_name='pic_hash')),
                ('pic_type', models.IntegerField(choices=[(0, 'X光图'), (1, 'CT图'), (2, '普通图片')], default=0, verbose_name='pic_type')),
                ('timestamp', models.BigIntegerField(verbose_name='timestamp')),
                ('saved_pos', models.CharField(max_length=50, verbose_name='saved_pos')),
                ('id_card', models.CharField(max_length=40, verbose_name='id_card')),
            ],
        ),
        migrations.CreateModel(
            name='medical_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('block', models.BooleanField(default=False)),
                ('passhash', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_name', models.CharField(max_length=30, verbose_name='own_name')),
                ('pic_hash', models.CharField(max_length=32, verbose_name='pic_hash')),
                ('pic_type', models.IntegerField(choices=[(0, 'X光图'), (1, 'CT图'), (2, '普通图片')], default=0, verbose_name='pic_type')),
                ('timestamp', models.BigIntegerField(verbose_name='timestamp')),
                ('saved_pos', models.CharField(max_length=50, verbose_name='saved_pos')),
                ('id_card', models.CharField(max_length=40, verbose_name='id_card')),
                ('status', models.IntegerField(choices=[(0, 'X光图'), (1, 'CT图'), (2, '普通图片')], default=0, verbose_name='status')),
            ],
            options={
                'db_table': 'uploadedimage',
            },
        ),
    ]
