# Generated by Django 2.0.3 on 2018-05-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eth_photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='operate_recoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_hash', models.CharField(max_length=32)),
                ('pic_timestamp', models.BigIntegerField()),
                ('operater_name', models.CharField(max_length=80)),
                ('operate_type', models.IntegerField()),
                ('operater_time', models.BigIntegerField()),
            ],
        ),
    ]
